// <auto-generated />
using System;
using API_LuckyDraw.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_LuckyDraw.Data.Migrations
{
    [DbContext(typeof(LuckyDrawDbContext))]
    [Migration("20220610190021_createdatabase")]
    partial class createdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_LuckyDraw.Model.GIFT", b =>
                {
                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<int?>("CODEUSAGELIMIT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODE");

                    b.ToTable("GIFT");
                });
#pragma warning restore 612, 618
        }
    }
}
